name: tests

on: [push, pull_request]

jobs:
  tests:
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
        numpy-version: ['1.20.3', '1.21.6', '1.22.4', '1.23.5']
        os: [ubuntu-latest, macos-11, macos-12]
        exclude:
        - python-version: '3.10'
          numpy-version: '1.20.3'
        - python-version: '3.11'
          numpy-version: '1.20.3'
        - python-version: '3.11'
          numpy-version: '1.21.6'
        - python-version: '3.11'
          numpy-version: '1.22.4'

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        python -m pip install --upgrade setuptools==59.8.0
        python -m pip install pytest
        python -m pip install numpy==${{ matrix.numpy-version }}
    - name: Install ufunclab
      run: |
        python -m pip install .
    - name: Test with pytest
      run: |
        cd ../..
        pwd
        export LOCATION=`python -c "import ufunclab, os; print(os.path.dirname(ufunclab.__file__))"`
        echo $LOCATION
        python -m pytest $LOCATION

  test-main-numpy:
    strategy:
      matrix:
          python-version: ['3.8', '3.10', '3.11']
          os: [ubuntu-20.04, ubuntu-latest]
          exclude:
          - python-version: '3.11'
            os: ubuntu-20.04

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        python -m pip install --upgrade setuptools==59.8.0
        python -m pip install pytest
        pushd .
        cd ..
        git clone --shallow-submodules --recurse-submodules https://github.com/numpy/numpy.git
        cd numpy
        python -m pip install .
        popd
    - name: Install ufunclab
      run: |
        python -m pip install .
    - name: Test with pytest
      run: |
        cd ../..
        pwd
        export LOCATION=`python -c "import ufunclab, os; print(os.path.dirname(ufunclab.__file__))"`
        echo $LOCATION
        python -m pytest $LOCATION
