name: tests

on: [push, pull_request]

jobs:
  test-older-py:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.8', '3.9']
        numpy-version: [1.20.3, 1.21.6, 1.22.4]

    steps:
    - uses: actions/checkout@v3
    - name: Set up ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install pytest
        python -m pip install numpy==${{ matrix.numpy-version }}
    - name: Install ufunclab
      run: |
        python -m pip install .
    - name: Test with pytest
      run: |
        cd ../..
        pwd
        export LOCATION=`python -c "import ufunclab, os; print(os.path.dirname(ufunclab.__file__))"`
        echo $LOCATION
        python -m pytest $LOCATION

  test-py3-10:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.10']
        numpy-version: [1.21.6, 1.22.4, 1.23.4]

    steps:
    - uses: actions/checkout@v3
    - name: Set up ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install pytest
        python -m pip install numpy==${{ matrix.numpy-version }}
    - name: Install ufunclab
      run: |
        python -m pip install .
    - name: Test with pytest
      run: |
        cd ../..
        pwd
        export LOCATION=`python -c "import ufunclab, os; print(os.path.dirname(ufunclab.__file__))"`
        echo $LOCATION
        python -m pytest $LOCATION

  test-py3-11:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11']
        numpy-version: [1.23.4]

    steps:
    - uses: actions/checkout@v3
    - name: Set up ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install pytest
        python -m pip install numpy==${{ matrix.numpy-version }}
    - name: Install ufunclab
      run: |
        python -m pip install .
    - name: Test with pytest
      run: |
        cd ../..
        pwd
        export LOCATION=`python -c "import ufunclab, os; print(os.path.dirname(ufunclab.__file__))"`
        echo $LOCATION
        python -m pytest $LOCATION

  test-main-numpy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install pytest
        pushd .
        cd ..
        git clone --shallow-submodules --recurse-submodules https://github.com/numpy/numpy.git
        cd numpy
        python -m pip install .
        popd
    - name: Install ufunclab
      run: |
        python -m pip install .
    - name: Test with pytest
      run: |
        cd ../..
        pwd
        export LOCATION=`python -c "import ufunclab, os; print(os.path.dirname(ufunclab.__file__))"`
        echo $LOCATION
        python -m pytest $LOCATION

  test-older-ubuntu-main-numpy:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install pytest
        pushd .
        cd ..
        git clone --shallow-submodules --recurse-submodules https://github.com/numpy/numpy.git
        cd numpy
        python -m pip install .
        popd
    - name: Install ufunclab
      run: |
        python -m pip install .
    - name: Test with pytest
      run: |
        cd ../..
        pwd
        export LOCATION=`python -c "import ufunclab, os; print(os.path.dirname(ufunclab.__file__))"`
        echo $LOCATION
        python -m pytest $LOCATION
