name: tests

on: [push, pull_request]

jobs:

  test-windows-2019:

    runs-on: windows-2019

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        architecture: 'x64'
        cache: 'pip'
        cache-dependency-path: 'environment.yml'

    - name: Install rtools (mingw-w64)
      run: |
        choco install rtools -y --no-progress --force --version=4.0.0.20220206
        echo "c:\rtools40\ucrt64\bin;" >> $env:GITHUB_PATH

    - name: Show gcc version
      run: |
        gcc --version

    - name: Install Python dependencies
      run: |
        pip install numpy==1.22.4 meson ninja meson-python pytest toml

    - name: Build
      run: |
        pip install .

    #- name: Test
    #  run: |
    #    cd ../..
    #    pwd
    #    export LOCATION=`python -c "import ufunclab, os; print(os.path.dirname(ufunclab.__file__))"`
    #    echo $LOCATION
    #    python -m pytest $LOCATION
