name: tests

on: [push, pull_request]

jobs:

  test-windows-2019:

    runs-on: windows-2019

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        architecture: 'x64'
        cache: 'pip'
        cache-dependency-path: 'environment.yml'

    - name: Install rtools (mingw-w64)
      run: |
        choco install rtools -y --no-progress --force --version=4.0.0.20220206
        echo "c:\rtools40\ucrt64\bin;" >> $env:GITHUB_PATH

    - name: Show gcc version
      run: |
        gcc --version

    - name: Install Python dependencies
      run: |
        pip install numpy==1.22.4 meson ninja meson-python pytest toml

    - name: Build
      run: |
        meson setup build
        ninja -v -j 1 -C build
        pip -v install --no-build-isolation .

    - name: Test
      run: |
        pytest --pyargs ufunclab -k abs_squared
        pytest --pyargs ufunclab -k tri_area
        pytest --pyargs ufunclab -k minmax
        pytest --pyargs ufunclab -k sosfilter
        pytest --pyargs ufunclab -k vdot
        pytest --pyargs ufunclab -k logistic
        pytest --pyargs ufunclab -k yeo_johnson
        pytest --pyargs ufunclab -k normal
